//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_resources {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game_resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Já jsem tady král.
        /// </summary>
        public static string CharacterKingDescription {
            get {
                return ResourceManager.GetString("CharacterKingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Kral.
        /// </summary>
        public static string CharacterKingName {
            get {
                return ResourceManager.GetString("CharacterKingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný konec.
        /// </summary>
        public static string cmd_exit {
            get {
                return ResourceManager.GetString("cmd_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný jdi.
        /// </summary>
        public static string cmd_go {
            get {
                return ResourceManager.GetString("cmd_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný mluv.
        /// </summary>
        public static string cmd_talk {
            get {
                return ResourceManager.GetString("cmd_talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Konec hry.
        /// </summary>
        public static string CommandAnswerEnd {
            get {
                return ResourceManager.GetString("CommandAnswerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Kam.
        /// </summary>
        public static string CommandAnswerWhere {
            get {
                return ResourceManager.GetString("CommandAnswerWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ským.
        /// </summary>
        public static string CommandAnswerWho {
            get {
                return ResourceManager.GetString("CommandAnswerWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bonbon. Co víc..
        /// </summary>
        public static string ItemCandyDescription {
            get {
                return ResourceManager.GetString("ItemCandyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bonbon.
        /// </summary>
        public static string ItemCandyName {
            get {
                return ResourceManager.GetString("ItemCandyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tu mas bonbonek!.
        /// </summary>
        public static string KingGiveItem {
            get {
                return ResourceManager.GetString("KingGiveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nic nereknu a bonbon uz jsi dostal!.
        /// </summary>
        public static string KingGiven {
            get {
                return ResourceManager.GetString("KingGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nic nereknu!.
        /// </summary>
        public static string KingNothing {
            get {
                return ResourceManager.GetString("KingNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jsi v temné komoře.
        /// </summary>
        public static string RoomChamberDesctiption {
            get {
                return ResourceManager.GetString("RoomChamberDesctiption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Komora.
        /// </summary>
        public static string RoomChamberName {
            get {
                return ResourceManager.GetString("RoomChamberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jsi v lese.
        /// </summary>
        public static string RoomForestDescription {
            get {
                return ResourceManager.GetString("RoomForestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Les.
        /// </summary>
        public static string RoomForrestName {
            get {
                return ResourceManager.GetString("RoomForrestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Kolem tebe je.
        /// </summary>
        public static string StateAroundYou {
            get {
                return ResourceManager.GetString("StateAroundYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nový předmět.
        /// </summary>
        public static string StateNewItem {
            get {
                return ResourceManager.GetString("StateNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Uvnitř vidíš.
        /// </summary>
        public static string StateSeeInside {
            get {
                return ResourceManager.GetString("StateSeeInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Máš v inventáři.
        /// </summary>
        public static string StateYouHave {
            get {
                return ResourceManager.GetString("StateYouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Odpověď.
        /// </summary>
        public static string TalkAnswer {
            get {
                return ResourceManager.GetString("TalkAnswer", resourceCulture);
            }
        }
    }
}
